-- ============================================================
-- 011 — Give a published routine an identity, and replace it atomically.
--
-- PROBLEM (confirmed):
--   TimetableEngineService.publishToRoutines() deleted only the batches
--   present in the payload it was about to insert:
--
--       for (final batch in rows.map((r) => r.batch).toSet())
--         delete().eq('batch', batch);
--       insert(payload);
--
--   Publish routine A, then routine B, and every batch that existed in A but
--   not in B survived. Students saw A and B merged. The delete loop and the
--   insert were also separate statements, so a failure between them left the
--   database holding a half-cleared routine.
--
-- FIX:
--   * routine_versions   — one row per published routine; exactly one active.
--   * routines.routine_version_id — which routine a class belongs to.
--   * publish_routine()  — swaps the whole routine inside ONE transaction.
--
-- `routines` keeps only the active routine's rows, so republishing does not
-- grow the table. History lives in routine_versions (and timetable_runs).
--
-- Idempotent.
-- ============================================================

-- ─── routine_versions ───────────────────────────────────────
create table if not exists public.routine_versions (
  id             uuid primary key default gen_random_uuid(),
  semester_label text,
  -- 'engine' = generated by the CP-SAT solver, 'upload' = parsed from a
  -- rendered workbook. Both go through the same publish path.
  source         text not null default 'engine'
                 check (source in ('engine', 'upload', 'manual')),
  is_active      boolean not null default false,
  row_count      int not null default 0,
  stats          jsonb not null default '{}'::jsonb,
  validation     jsonb not null default '{}'::jsonb,
  notes          text,
  published_at   timestamptz,
  published_by   uuid references auth.users(id),
  created_at     timestamptz not null default now()
);

-- At most one active routine, enforced by the database rather than by hope.
create unique index if not exists routine_versions_one_active
  on public.routine_versions (is_active) where is_active;

alter table public.routines
  add column if not exists routine_version_id uuid
    references public.routine_versions(id) on delete cascade,
  -- Service / non-CSE classes (GED, EEE taught to other departments) hold real
  -- teacher and room time. They were generated but never published, so Room
  -- Availability and Find Teacher reported those rooms free.
  add column if not exists is_service boolean not null default false;

create index if not exists routines_version_idx
  on public.routines (routine_version_id);
create index if not exists routines_lookup_idx
  on public.routines (batch, section, day);
create index if not exists routines_teacher_idx
  on public.routines (teacher_code, day);

-- ─── keep cancellation history across a republish ───────────
-- cancellations.routine_id was ON DELETE CASCADE, so every republish silently
-- deleted the entire cancellation history while the matching class_cancel
-- notifications stayed behind. The row carries its own batch/section/subject/
-- day/time_start, so it stays meaningful with a null routine_id.
do $$
declare c_name text;
begin
  select conname into c_name
    from pg_constraint
   where conrelid = 'public.cancellations'::regclass
     and contype = 'f'
     and pg_get_constraintdef(oid) like '%routines(id)%';
  if c_name is not null then
    execute format('alter table public.cancellations drop constraint %I', c_name);
  end if;
end $$;

alter table public.cancellations
  add constraint cancellations_routine_id_fkey
  foreign key (routine_id) references public.routines(id) on delete set null;

-- ─── RLS ────────────────────────────────────────────────────
alter table public.routine_versions enable row level security;

drop policy if exists "routine_versions_select" on public.routine_versions;
create policy "routine_versions_select" on public.routine_versions
  for select to authenticated using (true);

drop policy if exists "routine_versions_write_admin" on public.routine_versions;
create policy "routine_versions_write_admin" on public.routine_versions
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── atomic publish ─────────────────────────────────────────
-- One statement for the caller, one transaction for the database: the old
-- routine cannot be cleared unless the new one lands.
create or replace function public.publish_routine(
  p_rows           jsonb,
  p_semester_label text default null,
  p_source         text default 'engine',
  p_stats          jsonb default '{}'::jsonb,
  p_validation     jsonb default '{}'::jsonb,
  p_notes          text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id    uuid;
  v_count int;
begin
  if not public.is_admin() then
    raise exception 'Only an admin may publish a routine.'
      using errcode = '42501';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array'
     or jsonb_array_length(p_rows) = 0 then
    -- Refuse rather than wipe: an empty payload used to be a silent no-op
    -- that could still have cleared rows under the old delete-loop.
    raise exception 'Refusing to publish an empty routine.'
      using errcode = '22023';
  end if;

  insert into public.routine_versions
    (semester_label, source, published_by, stats, validation, notes)
  values (p_semester_label, p_source, auth.uid(), coalesce(p_stats, '{}'::jsonb),
          coalesce(p_validation, '{}'::jsonb), p_notes)
  returning id into v_id;

  -- Replace, never merge. Every previous class goes, including batches that
  -- do not appear in the incoming routine.
  update public.routine_versions set is_active = false where is_active;
  delete from public.routines;

  insert into public.routines
    (day, time_start, time_end, subject, subject_code, teacher_name,
     teacher_code, room, batch, section, semester, is_active, is_service,
     routine_version_id)
  select r.day, r.time_start::time, r.time_end::time, r.subject, r.subject_code,
         r.teacher_name, r.teacher_code, r.room, r.batch, r.section,
         coalesce(r.semester, 0), true, coalesce(r.is_service, false), v_id
    from jsonb_to_recordset(p_rows) as r(
      day text, time_start text, time_end text, subject text,
      subject_code text, teacher_name text, teacher_code text, room text,
      batch text, section text, semester int, is_service boolean);
  get diagnostics v_count = row_count;

  update public.routine_versions
     set is_active = true, row_count = v_count, published_at = now()
   where id = v_id;

  return jsonb_build_object('version_id', v_id, 'row_count', v_count);
end $$;

revoke execute on function public.publish_routine(jsonb, text, text, jsonb, jsonb, text)
  from anon, public;
grant execute on function public.publish_routine(jsonb, text, text, jsonb, jsonb, text)
  to authenticated;

comment on function public.publish_routine is
  'Atomically replaces the entire active routine. Deletes every previous class '
  '(not just colliding batches), inserts the new rows, and flips the active '
  'routine_versions row. Admin only.';

-- ─── adopt whatever is already in `routines` ────────────────
-- Existing installs have classes with no version. Claim them as one active
-- version so the "read the active routine" contract holds from the start.
do $$
declare v_id uuid;
begin
  if exists (select 1 from public.routines where routine_version_id is null)
     and not exists (select 1 from public.routine_versions where is_active) then
    insert into public.routine_versions
      (semester_label, source, is_active, published_at, notes)
    values ('Adopted (pre-versioning)', 'manual', true, now(),
            'Created by migration 011 to claim rows published before routine '
            'versioning existed.')
    returning id into v_id;

    update public.routines
       set routine_version_id = v_id
     where routine_version_id is null;

    update public.routine_versions
       set row_count = (select count(*) from public.routines where routine_version_id = v_id)
     where id = v_id;
  end if;
end $$;
